[general]
	#The Application ID of the Discord App to use. Replace this with your client id from the discord dashboard to change the name of the app
	applicationID = 1249146912330878997
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen. ONLY AVAILABLE WHEN CLOTH CONFIG IS INSTALLED!
	configScreen = true
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 18

[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "Entrando no Modpack"
	#The second line of text under the app name
	state = "Carregando..."
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["logo_discord512"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Um servidor de modpack da %mcver%"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["ilha_sky"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods instalados"
	#The buttons to display on Discord 

	[[init.buttons]]
		label = "CurseForge"
		url = "https://legacy.curseforge.com/minecraft/modpacks/skyxp"

[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "%player% Está no menu principal"
	#The second line of text under the app name
	state = "Observando o menu"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["logo_discord512"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Um servidor de modpack da %mcver%"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["ilha_sky"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods instalados"
	#The buttons to display on Discord 

	[[main_menu.buttons]]
		label = "CurseForge"
		url = "https://www.curseforge.com/minecraft/modpacks/mekaminers"

[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "%player% Indo jogar no SkyXP!"
	#The second line of text under the app name
	state = "Se juntando a nossa comunidade"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["logo_discord512"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Um Servidor de modpack %mcver%"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["ilha_sky"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods instalados"
	#The buttons to display on Discord 

	[[server_list.buttons]]
		label = "CurseForge"
		url = "https://www.curseforge.com/minecraft/modpacks/mekaminers"

	[[server_list.buttons]]
		label = "Technic"
		url = "https://www.technicpack.net/modpack/mekaminers.1931118"


[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true
	#The first line of text under the app name
	description = "Procurando por um Realm?"
	#The second line of text under the app name
	state = "É sério isso?"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["logo_discord512"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "?"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["ilha_sky"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods instalados"
	#The buttons to display on Discord 

	[[realms_list.buttons]]
		label = "CurseForge"
		url = "https://www.curseforge.com/minecraft/modpacks/mekaminers"

	[[realms_list.buttons]]
		label = "Technic"
		url = "https://www.technicpack.net/modpack/mekaminers.1931118"


[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "Entrando no jogo"
	#The second line of text under the app name
	state = "Entrando no mapa"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["logo_discord512"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Um Servidor de modpack %mcver%"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["ilha_sky"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods instalados"
	#The buttons to display on Discord 

	[[join_game.buttons]]
		label = "CurseForge"
		url = "https://www.curseforge.com/minecraft/modpacks/mekaminers"

	[[join_game.buttons]]
		label = "Technic"
		url = "https://www.technicpack.net/modpack/mekaminers.1931118"


[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Jogando no mundo: %world%"
	#The second line of text under the app name
	state = "Jogando SinglePlayer"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["logo_discord512"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Um Servidor de modpack %mcver%"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["ilha_sky"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods instalados"
	#The buttons to display on Discord 

	[[single_player.buttons]]
		label = "CurseForge"
		url = "https://www.curseforge.com/minecraft/modpacks/mekaminers"

	[[single_player.buttons]]
		label = "Technic"
		url = "https://www.technicpack.net/modpack/mekaminers.1931118"


[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Jogando no SkyXP com %players% players"
	#The second line of text under the app name
	state = "Jogando com amigos"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["logo_discord512"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Um Servidor de modpack %mcver%"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["ilha_sky"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods instalados"
	#The buttons to display on Discord 

	[[multi_player.buttons]]
		label = "CurseForge"
		url = "https://www.curseforge.com/minecraft/modpacks/mekaminers"

	[[multi_player.buttons]]
		label = "Technic"
		url = "https://www.technicpack.net/modpack/mekaminers.1931118"


[realms]
	#Enable/Disable the Realms Game Event
	enabled = true
	#The first line of text under the app name
	description = "Jogando no %realmname%"
	#The second line of text under the app name
	state = "Jogando em um Realm"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["logo_discord512"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Um Servidor de modpack %mcver%"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["ilha_sky"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%realmdescription%"
	#The buttons to display on Discord 

	[[realms.buttons]]
		label = "CurseForge"
		url = "https://www.curseforge.com/minecraft/modpacks/mekaminers"

	[[realms.buttons]]
		label = "Technic"
		url = "https://www.technicpack.net/modpack/mekaminers.1931118"


[generic]
	#The first line of text under the app name
	description = "Jogando SkyXP!"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["logo_discord512"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Um Servidor de modpack %mcver%"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["ilha_sky"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods instalados"
	#The buttons to display on Discord 

	[[generic.buttons]]
		label = "CurseForge"
		url = "https://www.curseforge.com/minecraft/modpacks/mekaminers"

	[[generic.buttons]]
		label = "Technic"
		url = "https://www.technicpack.net/modpack/mekaminers.1931118"


[custom]
	#Must these variables be parsed along with other variables
	enabled = true
	#Your custom variables to add
	variables = []

[dimension_overrides]
	enabled = false

	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "%player% is in The Overworld"
		state = ""
		largeImageKey = []
		largeImageText = "In the Overworld"
		smallImageKey = []
		smallImageText = "%mods% mods installed"
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = "%player% is in The Nether"
		state = ""
		largeImageKey = ["https://media.discordapp.net/attachments/1225518866784850032/1252833359319793694/logo_discord.png?ex=6673a77d&is=667255fd&hm=199ab9cf005e86c577a1e1ada2d135c3f2138d6cbb8efe45f63d05c910a829b3&=&format=webp&quality=lossless"]
		largeImageText = "In the Nether"
		smallImageKey = ["https://media.discordapp.net/attachments/1225518866784850032/1252833358849773681/IlhaSky.png?ex=6673a77d&is=667255fd&hm=a1ff2187bb520dc5cae7ba0bea519f9700bc3a4d149be8907ba2b03214eb76e0&=&format=webp&quality=lossless"]
		smallImageText = "%mods% mods installed"
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = "%player% is in The End"
		state = ""
		largeImageKey = ["https://media.discordapp.net/attachments/1225518866784850032/1252833359319793694/logo_discord.png?ex=6673a77d&is=667255fd&hm=199ab9cf005e86c577a1e1ada2d135c3f2138d6cbb8efe45f63d05c910a829b3&=&format=webp&quality=lossless"]
		largeImageText = "In the End"
		smallImageKey = ["https://media.discordapp.net/attachments/1225518866784850032/1252833358849773681/IlhaSky.png?ex=6673a77d&is=667255fd&hm=a1ff2187bb520dc5cae7ba0bea519f9700bc3a4d149be8907ba2b03214eb76e0&=&format=webp&quality=lossless"]
		smallImageText = "%mods% mods installed"
		buttons = []


