
["Grow speed"]
	#Range: 0.0 ~ 1.0
	grow_speed = 0.2

["Grow range"]
	#Range: 1 ~ 128
	grow_range = 4

["Grow height"]
	#Range: 1 ~ 64
	grow_height = 2

["Blacklist blocks"]
	blacklist = ["minecraft:netherrack", "minecraft:warped_nylium", "minecraft:crimson_nylium", "minecraft:grass_block", "minecraft:grass", "minecraft:tall_grass"]

["Activate Mystical Agriculture"]
	activate_myst_agri = false

["Enable posts"]
	enable_posts = true

["Should spawn particles"]
	spawn_particles = true

